### ISSUE TITLE
Make Header Name Dynamic through Environment Variable

### ISSUE THREAD

**Issue by koladev32** [Transfa/sendhooks-engine#40]
### Description
The current implementation has the header name `"X-Secret-Hash"` hardcoded. To improve configurability and flexibility, it would be beneficial to allow this header name to be set dynamically via an environment variable. If the environment variable is not set, the application should fall back to using `"X-Secret-Hash"` as the default header name.

### Tasks
- [ ] Update the code to read the header name from an environment variable.
- [ ] Implement a fallback mechanism to use `"X-Secret-Hash"` as the default header name if the environment variable is not set.
- [ ] Test the application to ensure that the dynamic header name configuration works as expected, and that the application behaves correctly with the new setup.
